// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PQHkA8lLaORQ_kGfMx2Yph7kg1Aavxo',
    appId: '1:277297250206:web:688800ab0dce2b746e208f',
    messagingSenderId: '277297250206',
    projectId: 'store-app-bdb6b',
    authDomain: 'store-app-bdb6b.firebaseapp.com',
    storageBucket: 'store-app-bdb6b.appspot.com',
    measurementId: 'G-84GGR1DS9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTX53ARM-CbuOF1L5AFFuOwf4kBDiNMNI',
    appId: '1:277297250206:android:b5ba3d5cbe4335856e208f',
    messagingSenderId: '277297250206',
    projectId: 'store-app-bdb6b',
    storageBucket: 'store-app-bdb6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1XGJweUv1jEUwJj27sKuxovefzDn5GlQ',
    appId: '1:277297250206:ios:96ff03980b92742e6e208f',
    messagingSenderId: '277297250206',
    projectId: 'store-app-bdb6b',
    storageBucket: 'store-app-bdb6b.appspot.com',
    iosClientId: '277297250206-9807qchvar0nrocqkpu3upsskr7nohti.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1XGJweUv1jEUwJj27sKuxovefzDn5GlQ',
    appId: '1:277297250206:ios:96ff03980b92742e6e208f',
    messagingSenderId: '277297250206',
    projectId: 'store-app-bdb6b',
    storageBucket: 'store-app-bdb6b.appspot.com',
    iosClientId: '277297250206-9807qchvar0nrocqkpu3upsskr7nohti.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
